# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: "storybook:build"
          skip: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
